// This file was generated by liblab | https://liblab.com/

export interface GetSkaterStatsParams {
  cayenneExp: string;
  isAggregate?: boolean;
  isGame?: boolean;
  factCayenneExp?: string;
  include?: string;
  exclude?: string;
  sort?: string;
  dir?: string;
  start?: number;
  limit?: number;
}
