// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';
import { GetSkaterStatsParams } from './request-params';

export class SkatersService extends BaseService {
  /**
   * Retrieve skater leaders for a specific attribute.
   * @param {string} attribute - Skater attribute
   * @param {string} lang - Language code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getSkaterLeaders(attribute: string, lang: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/{lang}/leaders/skaters/{attribute}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('attribute', attribute);
    request.addPathParam('lang', lang);
    return this.client.call(request);
  }

  /**
   * Retrieve skater milestones.
   * @param {string} lang - Language code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getSkaterMilestones(lang: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/{lang}/milestones/skaters',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('lang', lang);
    return this.client.call(request);
  }

  /**
   * Retrieve skater information.
   * @param {string} lang - Language code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getSkaterInformation(lang: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/{lang}/skater',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('lang', lang);
    return this.client.call(request);
  }

  /**
   * Retrieve skater stats for a specific report.
   * @param {string} report - Skater report
   * @param {string} lang - Language code
   * @param {string} cayenneExp - Required
   * @param {boolean} [isAggregate] - Optional
   * @param {boolean} [isGame] - Optional
   * @param {string} [factCayenneExp] - Optional
   * @param {string} [include] - Optional
   * @param {string} [exclude] - Optional
   * @param {string} [sort] - Optional
   * @param {string} [dir] - Optional
   * @param {number} [start] - Optional
   * @param {number} [limit] - Optional (Note: a limit of -1 will return all results)
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getSkaterStats(
    report: string,
    lang: string,
    params: GetSkaterStatsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const request = new Request({
      method: 'GET',
      path: '/{lang}/skater/{report}',
      config: this.config,
      responseSchema: z.any(),
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('report', report);
    request.addPathParam('lang', lang);
    request.addQueryParam('isAggregate', params?.isAggregate);
    request.addQueryParam('isGame', params?.isGame);
    request.addQueryParam('factCayenneExp', params?.factCayenneExp);
    request.addQueryParam('include', params?.include);
    request.addQueryParam('exclude', params?.exclude);
    request.addQueryParam('cayenneExp', params?.cayenneExp);
    request.addQueryParam('sort', params?.sort);
    request.addQueryParam('dir', params?.dir);
    request.addQueryParam('start', params?.start);
    request.addQueryParam('limit', params?.limit);
    return this.client.call(request);
  }
}
