// This file was generated by liblab | https://liblab.com/

import { NhlStats } from 'nhl_stats';

(async () => {
  const nhlStats = new NhlStats({});

  const { data } = await nhlStats.miscellaneous.pingServer();

  console.log(data);
})();
