// This file was generated by liblab | https://liblab.com/

import { NhlStatsClient } from 'nhl_stats_client';

(async () => {
  const nhlStatsClient = new NhlStatsClient({});

  const { data } = await nhlStatsClient.miscellaneous.pingServer();

  console.log(data);
})();
