// This file was generated by liblab | https://liblab.com/

import { Environment } from './http/environment';
import { SdkConfig } from './http/types';
import { PlayersService } from './services/players';
import { SkatersService } from './services/skaters';
import { GoaliesService } from './services/goalies';
import { DraftService } from './services/draft';
import { TeamsService } from './services/teams';
import { SeasonService } from './services/season';
import { GameService } from './services/game';
import { MiscellaneousService } from './services/miscellaneous';

export class NhlStats {
  public readonly players: PlayersService;

  public readonly skaters: SkatersService;

  public readonly goalies: GoaliesService;

  public readonly draft: DraftService;

  public readonly teams: TeamsService;

  public readonly season: SeasonService;

  public readonly game: GameService;

  public readonly miscellaneous: MiscellaneousService;

  constructor(public config: SdkConfig) {
    const baseUrl = config.environment || config.baseUrl || Environment.DEFAULT;
    this.config = {
      ...config,
      baseUrl,
    };
    this.players = new PlayersService(this.config);

    this.skaters = new SkatersService(this.config);

    this.goalies = new GoaliesService(this.config);

    this.draft = new DraftService(this.config);

    this.teams = new TeamsService(this.config);

    this.season = new SeasonService(this.config);

    this.game = new GameService(this.config);

    this.miscellaneous = new MiscellaneousService(this.config);
  }

  set baseUrl(baseUrl: string) {
    this.players.baseUrl = baseUrl;
    this.skaters.baseUrl = baseUrl;
    this.goalies.baseUrl = baseUrl;
    this.draft.baseUrl = baseUrl;
    this.teams.baseUrl = baseUrl;
    this.season.baseUrl = baseUrl;
    this.game.baseUrl = baseUrl;
    this.miscellaneous.baseUrl = baseUrl;
  }

  set environment(environment: Environment) {
    this.players.baseUrl = environment;
    this.skaters.baseUrl = environment;
    this.goalies.baseUrl = environment;
    this.draft.baseUrl = environment;
    this.teams.baseUrl = environment;
    this.season.baseUrl = environment;
    this.game.baseUrl = environment;
    this.miscellaneous.baseUrl = environment;
  }

  set timeout(timeout: number) {
    this.players.timeout = timeout;
    this.skaters.timeout = timeout;
    this.goalies.timeout = timeout;
    this.draft.timeout = timeout;
    this.teams.timeout = timeout;
    this.season.timeout = timeout;
    this.game.timeout = timeout;
    this.miscellaneous.timeout = timeout;
  }
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
