// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { GetTeamStatsParams } from './request-params';

export class TeamsService extends BaseService {
  /**
   * Retrieve list of all teams.
   * @param {string} lang - Language code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamInformation(lang: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/{lang}/team', { lang: lang });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }

  /**
   * Retrieve team stats for a specific report.
   * @param {string} report - Team report
   * @param {string} lang - Language code
   * @param {boolean} [isAggregate] - Optional
   * @param {boolean} [isGame] - Optional
   * @param {string} [factCayenneExp] - Optional
   * @param {string} [include] - Optional
   * @param {string} [exclude] - Optional
   * @param {string} [cayenneExp] - Optional
   * @param {string} [sort] - Optional
   * @param {string} [dir] - Optional
   * @param {number} [start] - Optional
   * @param {number} [limit] - Optional (Note: a limit of -1 will return all results)
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getTeamStats(
    report: string,
    lang: string,
    params?: GetTeamStatsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/{lang}/team/{report}', { report: report, lang: lang });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.isAggregate) {
      options.queryParams['isAggregate'] = params?.isAggregate;
    }
    if (params?.isGame) {
      options.queryParams['isGame'] = params?.isGame;
    }
    if (params?.factCayenneExp) {
      options.queryParams['factCayenneExp'] = params?.factCayenneExp;
    }
    if (params?.include) {
      options.queryParams['include'] = params?.include;
    }
    if (params?.exclude) {
      options.queryParams['exclude'] = params?.exclude;
    }
    if (params?.cayenneExp) {
      options.queryParams['cayenneExp'] = params?.cayenneExp;
    }
    if (params?.sort) {
      options.queryParams['sort'] = params?.sort;
    }
    if (params?.dir) {
      options.queryParams['dir'] = params?.dir;
    }
    if (params?.start) {
      options.queryParams['start'] = params?.start;
    }
    if (params?.limit) {
      options.queryParams['limit'] = params?.limit;
    }
    return this.client.get(path, options);
  }

  /**
   * Retrieve list of all franchises.
   * @param {string} lang - Language code
   * @returns {Promise<HttpResponse<any>>} Successful response
   */
  async getFranchiseInformation(lang: string, requestConfig?: RequestConfig): Promise<HttpResponse<any>> {
    const path = this.client.buildPath('/{lang}/franchise', { lang: lang });
    const options: any = {
      responseSchema: z.any(),
      requestSchema: z.any(),
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    return this.client.get(path, options);
  }
}
